<a href="https://colab.research.google.com/github/Alishah625/Alishah625/blob/main/Assignment_1_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Inputs and ouputs**

In [ ]:
import torch

# Define the input tensor and the target tensor
x1 = torch.tensor([0.05])
x2 = torch.tensor([0.10])
t1 = torch.tensor([0.01])
t2 = torch.tensor([0.99])
print("First input :",x1)
print("second input :",x2)
print("first output :",t1)
print("second output :",t2)

First input : tensor([0.0500])
second input : tensor([0.1000])
first output : tensor([0.0100])
second output : tensor([0.9900])


Weights and Biases

In [ ]:
w1 = torch.tensor([0.15], requires_grad=True)
w2 = torch.tensor([0.20], requires_grad=True)
w3 = torch.tensor([0.25], requires_grad=True)
w4 = torch.tensor([0.30], requires_grad=True)
w5 = torch.tensor([0.40], requires_grad=True)
w6 = torch.tensor([0.45], requires_grad=True)
w7 = torch.tensor([0.50], requires_grad=True)
w8 = torch.tensor([0.55], requires_grad=True)
b1 = torch.tensor([0.35], requires_grad=True)
b2 = torch.tensor([0.60], requires_grad=True)

Forward pass
Hidden Layers

In [ ]:
H1=x1*w1+x2*w2+b1
print(H1)
sigmoid = torch.nn.Sigmoid()
# Apply the sigmoid function to the input tensor
H1 = sigmoid(H1)
# Print the output
print("Hidden layer H1 :",H1)
H2=x1*w3+x2*w4+b1
print(H2)
sigmoid = torch.nn.Sigmoid()
# Apply the sigmoid function to the input tensor
H2 = sigmoid(H2)
# Print the output
print("Hidden layer H2 :",H2)

tensor([0.3775], grad_fn=<AddBackward0>)
Hidden layer H1 : tensor([0.5933], grad_fn=<SigmoidBackward0>)
tensor([0.3925], grad_fn=<AddBackward0>)
Hidden layer H2 : tensor([0.5969], grad_fn=<SigmoidBackward0>)


Forward pass
Output layers

In [ ]:
y1=H1*w5 + H2*w6+ b2
print(y1)
sigmoid = torch.nn.Sigmoid()
# Apply the sigmoid function to the input tensor
y1 = sigmoid(y1)
# Print the output
print("First observed output:",y1)
y2=H1*w7 + H2*w8+ b2
print(y2)
sigmoid = torch.nn.Sigmoid()
# Apply the sigmoid function to the input tensor
y2 = sigmoid(y2)
# Print the output
print("First observed output:", y2)

tensor([1.1059], grad_fn=<AddBackward0>)
First observed output: tensor([0.7514], grad_fn=<SigmoidBackward0>)
tensor([1.2249], grad_fn=<AddBackward0>)
First observed output: tensor([0.7729], grad_fn=<SigmoidBackward0>)


TOTAL Error

In [ ]:
loss= (t1-y1)**2/2.0 + (t2-y2)**2/2.0
print("Total error :",loss)

Total error : tensor([0.2984], grad_fn=<AddBackward0>)


Backpropagation

In [ ]:
#ompute gradients
loss.backward()
print(w1,w2,w3,w4)
print(w5,w6,w7,w8)
print(w1.grad,w2.grad,w3.grad,w4.grad)
print(w5.grad,w6.grad,w7.grad,w8.grad)
print(b1,b2)
print(b1.grad,b2.grad)

tensor([0.1500], requires_grad=True) tensor([0.2000], requires_grad=True) tensor([0.2500], requires_grad=True) tensor([0.3000], requires_grad=True)
tensor([0.4000], requires_grad=True) tensor([0.4500], requires_grad=True) tensor([0.5000], requires_grad=True) tensor([0.5500], requires_grad=True)
tensor([0.0004]) tensor([0.0009]) tensor([0.0005]) tensor([0.0010])
tensor([0.0822]) tensor([0.0827]) tensor([-0.0226]) tensor([-0.0227])
tensor([0.3500], requires_grad=True) tensor([0.6000], requires_grad=True)
tensor([0.0187]) tensor([0.1004])


Updated Weights

In [ ]:
wu1= w1- w1.grad * 0.5
print("Updated weight 1:", wu1)
wu2= w2- w2.grad * 0.5
print("Updated weight 2:", w2)
wu3= w3- w3.grad * 0.5
print("Updated weight 3:", wu3)
wu4= w4- w4.grad * 0.5
print("Updated weight 4:", wu4)
wu5 = w5- w5.grad * 0.5
print("Updated weight 5:", wu5)
wu6 = w6- w6.grad * 0.5
print("Updated weight 6:", wu6)
wu7 = w7- w7.grad * 0.5
print("Updated weight 7:", wu7)
wu8 = w8- w8.grad * 0.5
print("Updated weight 8:", wu8)


Updated weight: tensor([0.1498], grad_fn=<SubBackward0>)
Updated weight: tensor([0.2000], requires_grad=True)
Updated weight: tensor([0.2498], grad_fn=<SubBackward0>)
Updated weight: tensor([0.2995], grad_fn=<SubBackward0>)
Updated weight: tensor([0.3589], grad_fn=<SubBackward0>)
Updated weight: tensor([0.4087], grad_fn=<SubBackward0>)
Updated weight: tensor([0.5113], grad_fn=<SubBackward0>)
Updated weight: tensor([0.5614], grad_fn=<SubBackward0>)


Forward pass with updated weights
Hidden layer outputs

In [ ]:
Hu1=x1*wu1+x2*wu2+b1.grad
print(Hu1)
sigmoid = torch.nn.Sigmoid()
# Apply the sigmoid function to the input tensor
Hu1 = sigmoid(Hu1)
# Print the output
print("Hidden layer Hu1 :",Hu1)
Hu2=x1*wu3+x2*wu4+b1.grad
print(Hu2)
sigmoid = torch.nn.Sigmoid()
# Apply the sigmoid function to the input tensor
Hu2 = sigmoid(Hu2)
# Print the output
print("Hidden layer Hu2 :",Hu2)


tensor([0.0462], grad_fn=<AddBackward0>)
Hidden layer Hu1 : tensor([0.5115], grad_fn=<SigmoidBackward0>)
tensor([0.0612], grad_fn=<AddBackward0>)
Hidden layer Hu2 : tensor([0.5153], grad_fn=<SigmoidBackward0>)


Output layer
with updated wights

In [ ]:
yu1=Hu1*wu5 + Hu2*wu6+ b2.grad
print(y1)
sigmoid = torch.nn.Sigmoid()
# Apply the sigmoid function to the input tensor
yu1 = sigmoid(yu1)
# Print the output
print("output  layer yu1 :",yu1)
yu2=Hu1*wu7 + Hu2*wu8+ b2.grad
print(y1)
sigmoid = torch.nn.Sigmoid()
# Apply the sigmoid function to the input tensor
yu2 = sigmoid(yu2)
# Print the output
print("output  layer yu1 :",yu2)

tensor([0.7514], grad_fn=<SigmoidBackward0>)
output  layer yu1 : tensor([0.6212], grad_fn=<SigmoidBackward0>)
tensor([0.7514], grad_fn=<SigmoidBackward0>)
output  layer yu1 : tensor([0.6573], grad_fn=<SigmoidBackward0>)


Total Error
 with updated weights

In [ ]:
loss_u= (t1-yu1)**2/2.0 + (t2-yu2)**2/2.0
print("Total error :",loss_u)

Total error : tensor([0.2421], grad_fn=<AddBackward0>)
