<a href="https://colab.research.google.com/github/Alishah625/Alishah625/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.kaggle.com/code/aakashns/pytorch-basics-linear-regression-from-scratch

In [ ]:
import torch
x = [0,1,2,2,4,5,6,7,8,8]
print(x)

[0, 1, 2, 2, 4, 5, 6, 7, 8, 8]


In [ ]:
print (x[4])


4


In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [ ]:

x = torch.tensor(3.0)
w = torch.tensor(4.0, requires_grad = True)
b= torch.tensor(3.0, requires_grad = True)
y = w*x +b
y1=w1*y
print("Result of the equation is: ", y)
y.backward()
print("Derivative of the equation at x = 3 is: ", x.grad)
print("Derivative of the equation at w = 3 is: ", w.grad)
print("Derivative of the equation at b = 3 is: ", b.grad)

Result of the equation is:  tensor(15., grad_fn=<AddBackward0>)
Derivative of the equation at x = 3 is:  None
Derivative of the equation at w = 3 is:  tensor(3.)
Derivative of the equation at b = 3 is:  tensor(1.)


In [ ]:
w = torch.rand(2, 3)
x = torch.rand(2, 3)
b=1


In [ ]:
y=w*x + b

In [ ]:
import torch
e=2.718
a = torch.tensor(4.0, requires_grad = True)
B= 1/(1+torch.exp(-a))
print(B)

tensor(0.9820, grad_fn=<MulBackward0>)


In [ ]:
B.backward()

In [ ]:
print('da/dB :', a.grad)

da/dB : tensor(0.0177)


In [ ]:

a = torch.tensor(0.0, requires_grad = True)
d=1/(torch.sin(a))
print(d)

tensor(inf, grad_fn=<MulBackward0>)


In [ ]:
d.backward()

In [ ]:
d.grad

<ipython-input-26-e81247674995>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  d.grad


In [ ]:

import torch
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')


In [ ]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [ ]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.5663, -0.0797,  0.8203],
        [-0.8827,  0.1315,  0.8235]], requires_grad=True)
tensor([-0.5402,  0.5691], requires_grad=True)


In [ ]:
# Define the model
def model(x):
    return x @ w.t() + b


In [ ]:
p = model(inputs)
print(p)

tensor([[ 70.7309, -19.6488],
        [ 96.4761, -15.4832],
        [ 85.6209, -10.8460],
        [ 84.1463, -53.3425],
        [ 88.3008,   9.9283]], grad_fn=<AddBackward0>)


In [ ]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
def mse(t1, t2):
    diff = t1 - t2
    diff2= t3-t4
    return torch.sum(diff * diff)+(diff2*diff2) / diff.numel()

In [ ]:
loss = mse(p, targets)
print(loss)

tensor(6800.4243, grad_fn=<DivBackward0>)


In [ ]:
 #ompute gradients
loss.backward()



In [ ]:
print(w)
print(w.grad)

tensor([[ 0.5663, -0.0797,  0.8203],
        [-0.8827,  0.1315,  0.8235]], requires_grad=True)
tensor([[  980.8732,  -172.5555,   191.6744],
        [-9279.9648, -9977.5947, -6126.1172]])


In [ ]:
print(b)
print(b.grad)

tensor([-0.5402,  0.5691], requires_grad=True)
tensor([   8.8550, -109.8785])


In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
print(w)

tensor([[ 0.5663, -0.0797,  0.8203],
        [-0.8827,  0.1315,  0.8235]], requires_grad=True)


In [ ]:
p = model(inputs)
loss = mse(p, targets)
print(loss)

tensor(614.0858, grad_fn=<DivBackward0>)


In [ ]:
for i in range(10):
    p = model(inputs)
    loss = mse(p, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


In [ ]:
p = model(inputs)
loss = mse(p, targets)
print(loss)
print(p)

tensor(437.6913, grad_fn=<DivBackward0>)
tensor([[ 66.1129,  68.4817],
        [ 91.0447, 100.2835],
        [ 84.6158, 126.1048],
        [ 73.5700,  34.3923],
        [ 86.5286, 120.8820]], grad_fn=<AddBackward0>)
